spring:
  application:
    name: xigua-ai-code
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xigua_ai_code_maker
    username: root
    password: rootAa123456
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.xigua.xiguaaicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn